# Template: protein + ligand prediction for Boltz-2
# Fill in the fields below and save as e.g. inputs/myproject/20260131T123000_myrun.yaml
# Do NOT include secrets (API keys) here — put them in .env or env vars.

meta:
  name: "prod-PDE3A-ensifentrine" # short descriptive name
  author: "kng"
  date: "2026-01-31"                   # optional, ISO date
  notes: "first-prod, predicting ensifentrine-PDE3A complex and testing affinity prediction and structural."

# Sequences: list each polymer or ligand as a mapping
# - For proteins: use `protein` with optional `id`, `sequence`, `cyclic` (bool)
# - For ligands: use `ligand` with `id` and either `smiles` or `ccd` (PDB Chemical Component ID)
sequences:
  - protein:
      id: A 
      #sequence is from 671-1093 of UniProt PDE3A_HUMAN (Q14432)
      sequence: "ILAPEPLVMDNLDSIMEQLNTWNFPIFDLVENIGRKCGRILSQVSYRLFEDMGLFEAFKIPIREFMNYFHALEIGYRDIPYHNRIHATDVLHAVWYLTTQPIPGLSTVINDHGSTSDSDSDSGFTHGHMGYVFSKTYNVTDDKYGCLSGNIPALELMALYVAAAMHDYDHPGRTNAFLVATSAPQAVLYNDRSVLENHHAAAAWNLFMSRPEYNFLINLDHVEFKHFRFLVIEAILATDLKKHFDFVAKFNGKVNDDVGIDWTNENDRLLVCQMCIKLADINGPAKCKELHLQWTDGIVNEFYEQGDEEASLGLPISPFMDRSAPQLANLQESFISHIVGPLCNSYDSAGLMPGKWVEDSDESGDTDDPEEEEEEAPAPNEEETCENNESPKKKTFKRRKIYCQITQHLLQNHKMWKKVIEEE"
      # cyclic: false   # optional

  # Example ligand entry (choose one of smiles or ccd)
  - ligand:
      id: L1
      smiles: "COc1cc2c(cc1OC)-c1c/c(=N/c3c(C)cc(C)cc3C)n(CCNC(N)=O)c(=O)n1CC2"
      # ccd: "ATP"     # alternative: use three-letter CCD code

# Optional prediction parameters (these are model-specific defaults)
# See documentation for parameter meanings and valid ranges.
recycling_steps: 5
sampling_steps: 200
diffusion_samples: 5
step_scale: 1.638
without_potentials: false
output_format: mmcif
concatenate_msas: false

# Affinity prediction specific options (if desired)
# Affinity is automatically predicted when a ligand is present
sampling_steps_affinity: 500
diffusion_samples_affinity: 10
affinity_mw_correction: false